### ISSUE TITLE
100% method coverage for Java SDK

### ISSUE THREAD

**Issue by v1r3n** [orkes-io/orkes-conductor-client#20]
- WorkflowClient:
  <img width="1077" alt="Screen Shot 2022-09-14 at 12 49 45" src="https://user-images.githubusercontent.com/32961921/190202309-64549708-fe61-4157-9470-2acd72ddc230.png">
- MetadataClient:
  <img width="1011" alt="Screen Shot 2022-09-14 at 12 50 35" src="https://user-images.githubusercontent.com/32961921/190202533-3ea9c78c-2e65-4ef8-b93c-10fa65083838.png">
- TaskClient:
  <img width="1063" alt="Screen Shot 2022-09-15 at 17 15 53" src="https://user-images.githubusercontent.com/32961921/190500323-1e31d622-0200-4cd9-9509-7cf59d14fd6d.png">
- AuthorizationClient:
  <img width="1116" alt="Screen Shot 2022-09-15 at 00 56 37" src="https://user-images.githubusercontent.com/32961921/190310603-2dd5f7d7-3e18-4cfc-864c-204403cec1d4.png">
- EventClient:
  <img width="957" alt="Screen Shot 2022-09-16 at 16 28 09" src="https://user-images.githubusercontent.com/32961921/190716083-c3dc6414-29ba-4edc-a199-442ef3e56d05.png">
- SecretClient: 
  <img width="984" alt="Screen Shot 2022-09-16 at 16 58 48" src="https://user-images.githubusercontent.com/32961921/190722721-9dada697-c380-4ee1-b48e-39e378123bbc.png">
- SchedulerClient:
  <img width="1052" alt="Screen Shot 2022-09-16 at 19 10 48" src="https://user-images.githubusercontent.com/32961921/190812795-905fd7aa-b106-41a1-b920-272206fa65ac.png">

**Comment by gardusig** [comment]
Added 100% coverage for metadata client: https://github.com/orkes-io/orkes-conductor-client/pull/25

**Comment by gardusig** [comment]
Method with partial tests: [workflowClient.skipTaskFromWorkflow](https://github.com/orkes-io/orkes-conductor-client/blob/2c470d5f35e80ab3f6a701a75fd6a6ed604bcc79/src/test/java/io/orkes/conductor/client/api/WorkflowClientTests.java#L70)

Explanation: it makes a valid request, but `500` response is received due to the task being already executed.
